# NumPy essential details 

* Library used for computation and processing of single and multi-dimensional array of elements.
* Smaller memory consumption and better runtime behavior 
* Installation Process :  pip install numpy -> import numpy as np
* it is short for " Numerical Python
* it is used for computation and processing of single and multidimensional array of element.
* Smaller memory consumption and better runtime behavior
* Can be used to store data of different forms : 1-d,2-d,3-d and so on

In [1]:
# Example:
import numpy as np
values = [20.1,20.4,12.3,43.5,54.4,23.5]
convert = np.array(values)
print(convert)
print(convert+20)

[20.1 20.4 12.3 43.5 54.4 23.5]
[40.1 40.4 32.3 63.5 74.4 43.5]


Example of 1-d, 2-d, and 3-d array
* shape:(4,)
* shape:(2,3)
* shape:(4,3,2)

### Why do we use Numpy

* Plain 'for-loop'
* List comprehension
* Map function
* Numpy vectorize

In [2]:
## Practical part starts from here : -->

import numpy as np


# Creating an array

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array([1,2,3], dtype=float)# dtype = data type which is float in this list
c = np.array([1,2,3], dtype=str)# dtype = data type which is string in this list
print(a)
print(c)

[1. 2. 3.]
['1' '2' '3']


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)



[[1 2 3]
 [4 5 6]]


2

In [32]:
len(b)

2

In [38]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(b)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [39]:
# Getting dimensions of a numpy array
b.ndim

3

### Why Use NumPy
* In Traditional Python Programming, we have lists that serve the purpose of arrays, but they are slow to process.
* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
* The object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
* Arrays are very frequently used in data science, where speed and resources are very important.

In [40]:
# Get a shape of a numpy array

b.shape

(1, 3, 3)

In [10]:
# To find the datatype

b.dtype

dtype('int64')

## Accessing/changing specific elements, rows & columns etc.

In [11]:
a1 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a1)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
a1.ndim

2

In [13]:
a1.shape  ## Here 2 are the outer elements of the array and 6 are the inner elements of the array 


(2, 6)

In [14]:
print(a1[0,3])
## Here 0 will be the 1st element of the outer array and 
# 3 is the position of the element which we want to print out 


4


In [15]:
a1 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [41]:
## Here if we want to print the 11 element from the array 

print(a1[1,4])

11


In [17]:
## Getting a specific row from a numpy array
a1[0,:]


array([1, 2, 3, 4, 5, 6])

In [18]:
## Getting a specific column from the numpy array
a1[:,1]

array([2, 8])

In [19]:
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [20]:
# Accessing a specific element from the array : 
print(a1[1,5])

12


In [21]:
## I want to change the element from the array

a1[0,3] = 40
print(a1)

[[ 1  2  3 40  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
## Change the 5th column in 1st row to 50
a1[0,4] = 50
print(a1)

[[ 1  2  3 40 50  6]
 [ 7  8  9 10 11 12]]


##  Zeroes/Ones in NumPy

**Numpy.zeros** and **Numpy.ones** are tools in Python that can be used to create arrays of zeros and ones, respectively. To create an array with ones at and below the given diagonal and zeros elsewhere, use the numpy.tri() method in Python Numpy.

In [23]:
## Example code of creating a zeroes array 
import numpy as np
int_zeroes = np.zeros((2,3),dtype=int) # for the data type integer
float_ones = np.ones((2,5),dtype=float) # for the data type float
print(int_zeroes)
print(float_ones)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### Why do we need to use zeroes and ones in numpy array in python 

* Initialization for Computations
* * **numpy.zeros**: Creates an array filled with zeros. This is useful when you need a placeholder for computations or to initialize weights, biases, or matrices in algorithms.
* * **numpy.ones**: Creates an array filled with ones. This is often used for scaling, normalization, or as a starting point for iterative algorithms.

In [49]:
vara = 'soh'
full_array = np.full((3,3),vara, dtype='str' )
print(full_array)

[['s' 's' 's']
 ['s' 's' 's']
 ['s' 's' 's']]


In [51]:
# If we want to create an random number numpy array 

# np.random.rand(4,4)
print(np.random.randint(14,33, size=(3,3)))
# Here 14 is the starting number and 33 is the ending number
# and size will be 3 x 3 means 3 columns and 3 rows.

[[20 14 21]
 [25 17 32]
 [29 23 24]]


In [56]:
# identity function work on the basis of identity matrix 
'''
[1., 0., 0., 0., 0.],
[0., 1., 0., 0., 0.],
[0., 0., 1., 0., 0.],
[0., 0., 0., 1., 0.],
[0., 0., 0., 0., 1.] Just like this 

'''
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
a = np.array([[1,2,3,4,5,6],
              [10,20,30,40,50,60],
              [12,22,32,42,52,62],
              [11,21,31,41,51,61],
              [13,24,34,44,54,64]])


a.ndim
a.shape

(5, 6)

In [62]:
a[ :3, -5:]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [22, 32, 42, 52, 62]])

#### Question #2
* Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeroes and ones such that the ones make a shape of "+"


In [63]:
import numpy as np
n = int(input("Enter a number : "))
z = np.zeros((n,n),dtype='int')
print(z)



[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# make the middle row and column all 1s

z[n//2,:] = 1
z[:,n//2] = 1

print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


### Some Arithmetic Operations with NumPy - Maths + Stats


In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a + 2
# after adding + 2 this will add this value to the whole
# numpy list which we have been created 

array([3, 4, 5, 6])

In [ ]:
a // 2

array([0, 1, 1, 2])

In [ ]:
# for checking the minimum value in the numpy array 

# a.min()  OR 
np.min(a)

np.int64(1)

In [ ]:
# for checking the maximum value in the numpy array
# a.max()  OR
np.max(a)

np.int64(4)

In [ ]:
# for checking the mean value in the numpy array 

# a.mean()  OR 
np.mean(a)

np.float64(2.5)